config/routes.rb
Rlms::Application.routes.draw do
  namespace :admin do
    get "base/index", :as => :admin
  end

  namespace :router do
    resources :config_files do
      collection do
        get :dhcp
        get :iptables
      end
    end
    resources :dhcps
    resources :tc_classids
    resources :flows
    resources :open_ports
    resources :forward_ports
    resources :services, :only => [:update, :index] do
      member do
        post :find
      end
    end
    resources :computers do
      member do
        post :pass
        post :block
      end
    end
    get "main" => "main#index", :as => :main
    put "main/update",          :as => :update_main
  end

  namespace :torrent do
    resources :items do
      collection do
        post :set_rate
      end
      resources :files
      resources :peers
    end
  end

  namespace :dwnl do
    resources :web_jobs do
      member do
        get :start
      end
    end
  end

  resources :fw_rules

  get 'user_groups' => 'user_groups#index', :as => :user_groups
  post 'user_group/:user_id/:group_id' => 'user_groups#update', :as => :update_user_group
  get 'group_permissions/' => 'group_permissions#index', :as => :group_permissions
  post 'group_permission/' => 'group_permissions#update', :as => :group_permission

  resources :users
  resource :session

  root 'sessions#new'
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/login' => 'sessions#new', :as => :login
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  include MenusSupport
  submenu :admin

  requires_permission "admin"
  
  def index
    @users = User.filtered_by_login(params[:q])
      .filtered_by_group_id(params[:group_id])
      .order("id DESC")
      .paginate(:page => params[:page], :per_page => 50)
    @groups = Group.all_groups
  end
  
  def update
    user = User.find params[:user_id]
    group = Group.find params[:group_id]
    if params[:value] == "true"
      user.groups << group
    else
      user.groups.delete group
    end
    render :nothing => true
  end

end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_group.html.erb
<td>
  <%= check_box_tag(:user_group, 1, user.in_group?(group.name), 
        :id => "user_#{user.id}_group_#{group.id}",
        :'data-url' => update_user_group_path(user.id, group.id))
  %>
  <%= indicator_tag "user_#{user.id}_group_#{group.id}" %>
</td>

app/views/user_groups/index.html.haml
%h1.page-header= "User groups"
%p
  = will_paginate @users
= form_tag user_groups_path, :method => :get do
  %p
    = 'Login'
    %br/
    = text_field_tag :q, params[:q]
    = submit_tag 'Filter'
  %p
    = 'Group'
    %br/
    = select_tag 'group_id', options_for_select([['All','']] + Group.all_as_pairs, params[:group_id].try(:to_i)), :onchange => "submit();"
%table.std
  %thead
    %tr
      %th= "User"
      - @groups.each do |group|
        %th= group.name
  %tbody
    - @users.each do |user|
      %tr
        %td= user.login
        = render :partial => 'group', :collection => @groups, :locals => {:user => user}
%p
  = will_paginate @users
= observe_input_field "name='user_group'", :with => "'?value=' + this.checked"