config/routes.rb
Rlms::Application.routes.draw do
  namespace :admin do
    get "base/index", :as => :admin
  end

  namespace :router do
    resources :config_files do
      collection do
        get :dhcp
        get :iptables
      end
    end
    resources :dhcps
    resources :tc_classids
    resources :flows
    resources :open_ports
    resources :forward_ports
    resources :services, :only => [:update, :index] do
      member do
        post :find
      end
    end
    resources :computers do
      member do
        post :pass
        post :block
      end
    end
    get "main" => "main#index", :as => :main
    put "main/update",          :as => :update_main
  end

  namespace :torrent do
    resources :items do
      collection do
        post :set_rate
      end
      resources :files
      resources :peers
    end
  end

  namespace :dwnl do
    resources :web_jobs do
      member do
        get :start
      end
    end
  end

  resources :fw_rules

  get 'user_groups' => 'user_groups#index', :as => :user_groups
  post 'user_group/:user_id/:group_id' => 'user_groups#update', :as => :update_user_group
  get 'group_permissions/' => 'group_permissions#index', :as => :group_permissions
  post 'group_permission/' => 'group_permissions#update', :as => :group_permission

  resources :users
  resource :session

  root 'sessions#new'
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/login' => 'sessions#new', :as => :login
end

app/models/r_torrent/item.rb
class RTorrent::Item < RTorrent::Base
  METHODS = {
    :get_creation_date => :creation_date,
    :get_free_diskspace => :free_diskspace,
    :get_base_filename => :base_filename,
    :get_base_path => :path,
    :get_directory => :directory,
    :get_message => :message,
    :get_hash => :hash,
    :get_hashing => :hashing,
    :get_name => :name,
    :get_left_bytes => :bytes_left,
    :get_size_bytes => :bytes_size,
    :get_chunk_size => :chunk_size,
    :get_size_chunks => :size_chunks,
    :get_completed_chunks => :completed_chunks,
    :get_down_rate => :down_rate,
    :get_up_rate => :up_rate,
    :get_priority => :priority,
    :get_connection_current => :connection_current,
    :get_complete => :complete,
    :get_local_id => :local_id,
    :is_active => :active,
    :is_multi_file => :multi_file,
  }.freeze

  PRIORITIES = { 
    'off' => 0,
    'low' => 1,
    'normal' => 2,
    'high' => 3,
  }
  
  attr_accessor *METHODS.values
  attr_accessor :torrent_url
  alias_method :id, :hash
  alias_method :to_param, :id

  class << self
    def remote_methods
      METHODS.keys.map{|k| "d.#{k.to_s}="}
    end
  end
  
  def initialize args=nil
    return if args.nil?
    METHODS.each_with_index do |m, i|
      arg = args.is_a?(String) ? call("d.#{m.first}", args) : args[i]
      send(:"#{m.last.to_s}=", arg)
    end
  end

  def raw_elements element_type
    call(*(["#{element_type.prefix}multicall", hash, ''] + element_type.remote_methods))
  end

  def mapped_elements element_type
    raw_elements(element_type).map{|r| element_type.new(r)}
  end
  
  def trackers
    mapped_elements(RTorrent::Tracker)
  end 
  
  def peers
    mapped_elements(RTorrent::Peer)
  end
  
  def files
    raw_elements(RTorrent::File).map{|r| RTorrent::File.new(r, hash)}
  end
  
  def bytes
    size_chunks * chunk_size
  end

  def percent_complete
    ((bytes_completed.to_f/bytes.to_f) * 100).to_i.to_s + '%'
  end

  def bytes_completed
    completed_chunks * chunk_size
  end
  
  def status
    s = "Downloading"
    s = "Stopped" unless active?
    s = "Complete" if complete?
    s = "Hashing" if hashing > 0
    s
  end

  def conn_type
    s = ""
    s = "Leeching" if active? && connection_current == "leech"
    s = "Seeding" if active? && connection_current == "seed"
    s
  end

  def active?
    active == 1
  end

  def complete?
    complete == 1
  end

  def start
    call('d.start', hash)
  end

  def stop
    call('d.stop', hash)
  end

  def close
    call('d.close', hash)
  end

  def destroy
    call('d.erase', hash)
  end
  alias_method :delete, :destroy
  
  def set_priority prio
    call("d.set_priority", hash, prio.to_i)
  end
  
  def created_at
    Time.at(creation_date).strftime("%d/%m/%Y %H:%M:%S")
  end
  
  def display_priority
    PRIORITIES.index(priority)
  end
  
  def eta
    dw_r = down_rate == 0 ?  0.01 : down_rate
    (bytes - bytes_completed)/dw_r
  end
  
  def time_left
    t = eta
    return t.to_s + 's' if t < 60
    return (t/60).to_s + 'min' if t < 3600
    return (t/3600).to_s + 'h' if t < 3600*24
    result = (t/(3600*24))
    result > 100 ? '--' : result.to_s + 'd'
  end
end

app/controllers/torrent/base_controller.rb
class Torrent::BaseController < ApplicationController
  include MenusSupport
  submenu :torrent

  protected

  def check_permission
    return unless authorize("torrent")
  end
end

app/controllers/torrent/files_controller.rb
class Torrent::FilesController < Torrent::BaseController
  def index
    @files = RTorrent::Item.new(params[:item_id]).files
  end

  def update
    files = RTorrent::Item.new(params[:item_id]).files
    params[:priorities].each do |i, prio|
      files[i.to_i].set_priority i.to_i, prio
    end
    redirect_to torrent_files_path(params[:item_id])
  end
end

app/controllers/torrent/items_controller.rb
class Torrent::ItemsController < Torrent::BaseController
  def index
    @torrents = RTorrent::Client.items
  rescue
    @torrents = []
    @r_error = $!
  ensure
    render :update do |page|
      page.replace_html 'downloading', :partial => 'torrent', :collection => @torrents, :locals => { :hashes => params[:hashes] || [] }
      page.replace_html 'stats', :partial => 'stats'
    end if request.xhr?
  end

  def show
    @torrent = RTorrent::Item.new(params[:id])
  end

  def new
    @torrent = RTorrent::Item.new
  end

  def create
    respond_to do |format|
      flash[:notice] = 'Torrent was successfully added.' if RTorrent::Client.upload([items_params[:torrents]])
      flash[:notice] = 'Torrent url was successfully added.' if RTorrent::Client.load_start(items_params[:torrent_url])
      format.html { redirect_to(new_torrent_item_url) }
    end
  end

  def update
    @commit = params[:commit].downcase
    @hashes = params[:hashes] || []
    @torrents = RTorrent::Client.items.select{|t| @hashes.include?(t.id)  }
    
    @torrents.each{|t| 
      @commit == 'update' ? t.set_priority(params[:priority]) : t.send(:"#{@commit}") 
    }

    respond_to do |format|
      flash[:notice] = 'Torrents were successfully updated.' unless @hashes.empty?
      flash[:error] = 'No torrents selected' if @hashes.empty?
      format.html { redirect_to(torrent_items_url) }
    end
  end

  def set_rate
    up = params[:bandwidth][:up]
    down = params[:bandwidth][:down]
    RTorrent::Client.set_upload_rate up unless up.blank?
    RTorrent::Client.set_download_rate down unless down.blank?
    render :nothing => :true
  end
  
  def destroy
    @torrent = RTorrent::Item.new params[:id]
    @torrent.destroy

    respond_to do |format|
      flash[:notice] = 'Torrent has been deleted.'
      format.html { redirect_to(torrent_items_url) }
    end
  end

  protected

  def items_params
    params.require(:torrent).permit(:torrent_url, :torrents)
  end
end

app/controllers/torrent/peers_controller.rb
class Torrent::PeersController < Torrent::BaseController
  def index
    @peers = RTorrent::Item.new(params[:item_id]).peers
  end
end

app/helpers/torrent/base_helper.rb
module Torrent::BaseHelper
end

app/helpers/torrent/items_helper.rb
module Torrent::ItemsHelper
  def tr_td_row name, value, options = { }
    content_tag :tr, content_tag(:td, name) + content_tag(:td, value), options
  end
  
  def tr_td_row_spacer
    tr_td_row '&nbsp;', '&nbsp;'
  end
end

app/views/torrent/items/_actions.html.haml
= small_btn_tag "Start"
= small_btn_tag "Stop"
= small_btn_tag "Delete"
= select_tag "priority", options_for_select(RTorrent::Item::PRIORITIES), class: 'select btn btn-primary btn-xs'
= small_btn_tag "Update"

app/views/torrent/items/_stats.html.erb
Bandwidth: 
[<%= RTorrent::Client.download_rate.to_kb -%>] <%= RTorrent::Client.down_rate.to_kb -%> 
[<%= RTorrent::Client.upload_rate.to_kb -%>] <%= RTorrent::Client.up_rate.to_kb -%>

<%= link_to 'Change', '#', onclick: "$('bandwidth_form').toggle();" -%>

app/views/torrent/items/_torrent.html.erb
<tr>
  <td><%= check_box_tag "hashes[]", torrent.id, hashes.include?(torrent.id), :id => "hash_#{torrent.id}" %></td>
  <td><%= label_tag("hash_#{torrent.id}", h(torrent.name)) %></td>
  <td><%=h torrent.bytes.to_mb -%></td>
  <td><%=h torrent.bytes_completed.to_mb %></td>
  <td><%=h torrent.percent_complete %></td>
  <td><%=h torrent.status %></td>
  <td><%=h torrent.down_rate.to_mb %></td>
  <td><%=h torrent.up_rate.to_mb %></td>
  <td><%=h torrent.display_priority %></td>
  <td><%=h torrent.time_left %></td>
  <td>
    <%= link_to 'Info', torrent_item_path(torrent) %>
    <%= link_to 'Files', torrent_item_files_path(torrent) %>
    <%= link_to 'Peers', torrent_item_peers_path(torrent) %>
  </td>
</tr>

app/views/torrent/items/edit.html.erb
<h1>Editing torrent</h1>

<% form_for(:torrent, :url => torrent_path(@torrent), :html => {:method => :put}) do |f| %>
  <p>
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :bytes %><br />
    <%= f.text_field :bytes %>
  </p>
  <p>
    <%= f.label :bytes_completed %><br />
    <%= f.text_field :bytes_completed %>
  </p>
  <p>
    <%= f.label :bytes_left %><br />
    <%= f.text_field :bytes_left %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', torrent_path(@torrent) %> |
<%= link_to 'Back', torrents_path %>

app/views/torrent/items/index.html.haml
%h1.page-header Listing torrents

- unless @r_error.present?
  = form_tag torrent_item_path(0), :method => :put, :id => "rform" do
    %table.std
      %thead
        %tr
          %th &nbsp;
          %th Name
          %th Size
          %th Downloaded
          %th Done
          %th Status
          %th Down speed
          %th Up speed
          %th Priority
          %th Time left
          %th Actions
      %tbody#downloading
        = render :partial => 'torrent', :collection => @torrents, :locals => {:hashes => []}
    = render :partial => 'actions'
  #stats
    = render :partial => 'stats'

  #bandwidth_form{:style => "display: none;"}
    = form_tag :url => set_rate_torrent_items_path, :success => "$('bandwidth_form').hide();", :remote => true do
      Down: #{text_field_tag "bandwidth[down]", RTorrent::Client.download_rate.to_kb, :size => 3}    Up: #{text_field_tag "bandwidth[up]", RTorrent::Client.upload_rate.to_kb, :size => 3}    #{submit_tag "Update"}
  %br/

  = link_to 'New torrent', new_torrent_item_path

- else
  = @r_error

app/views/torrent/items/new.html.haml
%h1.page-header New torrent

= simple_form_for(:torrent, url: torrent_items_path, html: {multipart: true}) do |f|
  = f.input :torrents, as: :file, label: 'Torrent file'
  = f.input :torrent_url
  = f.actions do |f|
    = f.submit "Create"
    = f.action "Cancel", torrent_items_path

app/views/torrent/items/show.html.erb
<table class="noborder">
  <tbody>
    <%= tr_td_row 'Name:', @torrent.name %>
    <%= tr_td_row 'Local id:', @torrent.local_id %>
    <%= tr_td_row 'Info hash:', @torrent.id %>
    <%= tr_td_row 'Created:', @torrent.created_at -%>
    <%= tr_td_row 'Tracker info', @torrent.message %>

    <%= tr_td_row_spacer -%>

    <%= tr_td_row 'Directory:', @torrent.directory %>
    <%= tr_td_row 'Base Path:', @torrent.path %>
    <%= tr_td_row 'Priority:', @torrent.display_priority %>

    <%= tr_td_row_spacer -%>

    <%= tr_td_row 'Connection type:', @torrent.conn_type %>
    <%= tr_td_row 'Bytes:', @torrent.bytes.to_mb %>
    <%= tr_td_row 'Bytes done:', @torrent.bytes_completed.to_mb %>

    <%= tr_td_row_spacer -%>

    <%= tr_td_row 'Download:', @torrent.down_rate.to_kb %>
    <%= tr_td_row 'Upload:', @torrent.up_rate.to_kb %>
  </tbody>
</table>

<%= link_to 'Files', torrent_item_files_path(@torrent) %> |
<%= link_to 'Back', torrent_items_path %>