config/routes.rb
Rlms::Application.routes.draw do
  namespace :admin do
    get "base/index", :as => :admin
  end

  namespace :router do
    resources :config_files do
      collection do
        get :dhcp
        get :iptables
      end
    end
    resources :dhcps
    resources :tc_classids
    resources :flows
    resources :open_ports
    resources :forward_ports
    resources :services, :only => [:update, :index] do
      member do
        post :find
      end
    end
    resources :computers do
      member do
        post :pass
        post :block
      end
    end
    get "main" => "main#index", :as => :main
    put "main/update",          :as => :update_main
  end

  namespace :torrent do
    resources :items do
      collection do
        post :set_rate
      end
      resources :files
      resources :peers
    end
  end

  namespace :dwnl do
    resources :web_jobs do
      member do
        get :start
      end
    end
  end

  resources :fw_rules

  get 'user_groups' => 'user_groups#index', :as => :user_groups
  post 'user_group/:user_id/:group_id' => 'user_groups#update', :as => :update_user_group
  get 'group_permissions/' => 'group_permissions#index', :as => :group_permissions
  post 'group_permission/' => 'group_permissions#update', :as => :group_permission

  resources :users
  resource :session

  root 'sessions#new'
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/login' => 'sessions#new', :as => :login
end

app/models/fw_rule.rb
class FwRule < ActiveRecord::Base
  scope :ip_table, lambda {|filter|
    filter = '%' if filter.nil? || (!filter.nil? && filter == '')
    {:conditions => ['lower(ip_table) like lower(?)', filter ]}
  }
  scope :chain, lambda {|filter|
    filter = '%' if filter.nil? || (!filter.nil? && filter == '')
    {:conditions => ['lower(chain_name) like lower(?)', filter ]}
  }

  TARGETS = ['ACCEPT', 'DROP','MARK', 'SNAT', 'DNAT'].freeze
  PROTOCOLS = ['ALL','TCP', 'UDP', 'ICMP'].freeze
  IN_INT = ['INPUT', 'FORWARD', 'PREROUTING']
  OUT_INT = ['OUTPUT', 'FORWARD', 'POSTROUTING']
  CMDS = ['A', 'I', 'P']

  def self.chain_names ip_table='filter'
    FwRuleContainer.chains_for(ip_table).map{|cn| [cn.to_s] }
  end

  def self.ip_tables
    FwRuleContainer.ip_tables.map{ |cn| [cn.to_s, cn.to_s.downcase] }
  end
  
  def self.blocked_ips
    FwRuleContainer.rules_for(:nat,'PREROUTING').map{ |chn| chn.src_ip.split('/').first unless chn.src_ip.blank? }
  end
  
  def self.blocking_rule computer, firewall
    return FwRule.new if firewall.blank? || computer.blank?
    FwRuleParser.new("-t nat -A PREROUTING -s #{computer.ip_address} -p tcp -m tcp --dport 1:65535 -j DNAT --to-destination #{firewall.blocking_ip_port}").parse
  end
  
  def self.passing_rule computer, firewall
    return FwRule.new if firewall.blank? || computer.blank?
    FwRuleParser.new("-t nat -A POSTROUTING -s #{computer.ip_address} -o #{firewall.ext_inf} -j SNAT --to-source #{firewall.auto_ext_ip}").parse
  end
  
  def self.block_computer computer, firewall
    ShellCommand.ip_tables blocking_rule(computer, firewall).to_ipt("D")
    ShellCommand.ip_tables blocking_rule(computer, firewall).to_ipt("A")
    ShellCommand.ip_tables passing_rule(computer, firewall).to_ipt("D")
  end
  
  def self.pass_computer computer, firewall
    ShellCommand.ip_tables blocking_rule(computer, firewall).to_ipt("D")
    ShellCommand.ip_tables passing_rule(computer, firewall).to_ipt("D")
    ShellCommand.ip_tables passing_rule(computer, firewall).to_ipt("A")
  end
  
  def to_ipt ipcmd=nil, rulenum=nil
    new_rule = self.clone
    new_rule.cmd = ipcmd if ipcmd
    new_rule.order = rulenum if rulenum
    result = ""
    [:ip_table, :cmd, :chain_name, :order, :src_ip, :dest_ip, :in_int, :out_int, 
     :protocol, :mod, :mod_option, :mod_protocol, :src_port, :dest_port, 
     :tcp_flags, :tcp_flags_option, :target, :aft_option, :aft_argument].each do |f|
      result += new_rule.value_of(f)
    end
    result.strip
  end
    
  def value_of field
    return "#{field_options[field.to_sym]}#{value_of_field(field)} " unless value_of_field(field).blank?
    ''
  end
  
  private
  
  def value_of_field field
    eval field.to_s if field
  end
  
  def field_options
    {
      :ip_table => "-t ",
      :cmd => "-",
      :src_ip => "-s ",
      :dest_ip => "-d ",
      :in_int => "-i ",
      :out_int => "-o ",
      :protocol => "-p ",
      :mod => "-m ",
      :mod_protocol => "-m ",
      :src_port => "--sport ",
      :dest_port => "--dport ",
      :tcp_flags => "--tcp-flags ",
      :target => "-j "
    }
  end
end

app/controllers/fw_rules_controller.rb
class FwRulesController < ApplicationController
  include MenusSupport
  submenu :firewall

  def index
    FwRuleContainer.read
    @filter = params[:filter].blank? ? 'filter' : params[:filter]
    @filter_chain = params[:filter_chain]
    @fw_rules = FwRuleContainer.rules_for(@filter, @filter_chain)
    @fw_rules = {@filter_chain.to_s => @fw_rules } if @fw_rules.is_a?(Array)
  end

  def show
    @fw_rule = FwRule.find_by_id(params[:id])
  end

  def new
    @fw_rule = FwRule.new
  end

  def edit
    @fw_rule = FwRule.find_by_id(params[:id])
  end

  def create
    @fw_rule = FwRule.new(params[:fw_rule])

    respond_to do |format|
      if @fw_rule.save
        flash[:notice] = 'FwRule was successfully created.'
        format.html { redirect_to(fw_rule_url(@fw_rule)) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @fw_rule = FwRule.find_by_id(params[:id])

    respond_to do |format|
      if @fw_rule.update_attributes(params[:fw_rule])
        flash[:notice] = 'FwRule was successfully updated.'
        format.html { redirect_to(fw_rule_url(@fw_rule)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @fw_rule = FwRule.find_by_id(params[:id])
    @fw_rule.destroy

    respond_to do |format|
      format.html { redirect_to(fw_rules_url) }
    end
  end

end

app/helpers/fw_rules_helper.rb
module FwRulesHelper
end

app/views/fw_rules/_form.html.erb
<p>
  <%= f.label :order %><br />
  <%= f.select :order, (1..FwRule.count+1).to_a %>
</p>
<p>
  <%= f.label :ip_table %><br />
  <%#= f.select :ip_table, FwRule::IP_TABLES %>
</p>
<p>
  <%= f.label :cmd %><br />
  <%= f.select :cmd, FwRule::CMDS %>
</p>
<p>
  <%= f.label :chain_name %><br />
  <%#= f.select :chain_name, FwRule::CHAIN_NAMES %>
</p>
<p>
  <%= f.label :in_int %><br />
  <%= f.text_field :in_int %>
</p>
<p>
  <%= f.label :out_int %><br />
  <%= f.text_field :out_int %>
</p>
<p>
  <%= f.label :protocol %><br />
  <%= f.select :protocol, FwRule::PROTOCOLS %>
</p>
<p>
  <%= f.label :src_ip %><br />
  <%= f.text_field :src_ip %>
</p>
<p>
  <%= f.label :src_port %><br />
  <%= f.text_field :src_port %>
</p>
<p>
  <%= f.label :dest_ip %><br />
  <%= f.text_field :dest_ip %>
</p>
<p>
  <%= f.label :dest_port %><br />
  <%= f.text_field :dest_port %>
</p>
<p>
  <%= f.label :mod %><br />
  <%= f.text_field :mod %>
</p>
<p>
  <%= f.label :target %><br />
  <%= f.select :target, FwRule::TARGETS %>
</p>

app/views/fw_rules/edit.html.erb
<h1>Editing fw_rule</h1>

<%= form_for(@fw_rule) do |f| %>
  <%= f.error_messages %>
  <%= render :partial => 'form', :locals => {:f => f} -%>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @fw_rule %> |
<%= link_to 'Back', fw_rules_path %>

app/views/fw_rules/index.html.haml
%h1.page-header
  Listing #{@filter.camelize} Rules
.form
  = form_tag fw_rules_path, :method => :get do
    IP table
    \#{select_tag 'filter', options_for_select(FwRule.ip_tables, @filter), :onchange => "submit();"}    IP chain
    \#{select_tag 'filter_chain', options_for_select([['select','']] + FwRule.chain_names(@filter), @filter_chain), :onchange => "submit();"}    #{link_to 'Raw Iptables', '#', :onclick => "$('#iptables_raw').toggle();"}
%pre#iptables_raw{:style => "display: none;"}
  = ShellCommand.ip_tables_list(@filter)
%table.std
  %thead
    %tr
      %th Order
      %th Target
      %th
        Src/Dest
        %br>/
        ip
      %th In/Out int
      %th Protocol
      %th
        Mod
        %br>/
        Protocol
      %th
        Src/Dest
        %br>/
        port
      %th Mod
      %th Action
  %tbody
    - @fw_rules.each do |chain_name,rules|
      %tr
        %td{:colspan => "9"}
          %h3= chain_name
      - for fw_rule in rules do
        - klass = cycle('',"gray")
        %tr{:class => klass}
          %td= h fw_rule.order
          %td= h fw_rule.target
          %td
            si: #{h fw_rule.src_ip}
            %br/
            di: #{h fw_rule.dest_ip}
          %td
            i: #{h fw_rule.in_int}
            %br/
            o: #{h fw_rule.out_int}
          %td= h fw_rule.protocol
          %td= h fw_rule.mod_protocol
          %td
            sp: #{h fw_rule.src_port}
            %br/
            dp: #{h fw_rule.dest_port}
          %td= h fw_rule.mod
          %td
        = link_to 'Edit', edit_fw_rule_path(0)
        %tr{:class => klass}
          %td &nbsp;
          %td{:colspan => "8"}
            = h fw_rule.aft_option
            = h fw_rule.aft_argument
            = h fw_rule.mod_option
            = h fw_rule.tcp_flags
            = h fw_rule.tcp_flags_option

= link_to 'New fw rule', new_fw_rule_path

app/views/fw_rules/new.html.erb
<h1>New fw_rule</h1>

<%= form_for(@fw_rule) do |f| %>
  <%= f.error_messages %>
  <%= render :partial => 'form', :locals => {:f => f} -%>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', fw_rules_path %>

app/views/fw_rules/show.html.erb
<p>
  <b>Order:</b>
  <%=h @fw_rule.order %>
</p>

<p>
  <b>Ip table:</b>
  <%=h @fw_rule.ip_table %>
</p>

<p>
  <b>Cmd:</b>
  <%=h @fw_rule.cmd %>
</p>

<p>
  <b>Chain name:</b>
  <%=h @fw_rule.chain_name %>
</p>

<p>
  <b>In int:</b>
  <%=h @fw_rule.in_int %>
</p>

<p>
  <b>Out int:</b>
  <%=h @fw_rule.out_int %>
</p>

<p>
  <b>Protocol:</b>
  <%=h @fw_rule.protocol %>
</p>

<p>
  <b>Src ip:</b>
  <%=h @fw_rule.src_ip %>
</p>

<p>
  <b>Src port:</b>
  <%=h @fw_rule.src_port %>
</p>

<p>
  <b>Dest ip:</b>
  <%=h @fw_rule.dest_ip %>
</p>

<p>
  <b>Dest port:</b>
  <%=h @fw_rule.dest_port %>
</p>

<p>
  <b>Mod:</b>
  <%=h @fw_rule.mod %>
</p>

<p>
  <b>Target:</b>
  <%=h @fw_rule.target %>
</p>

<%= link_to 'Edit', edit_fw_rule_path(@fw_rule) %> |
<%= link_to 'Back', fw_rules_path %>