config/routes.rb
Rlms::Application.routes.draw do
  namespace :admin do
    get "base/index", :as => :admin
  end

  namespace :router do
    resources :config_files do
      collection do
        get :dhcp
        get :iptables
      end
    end
    resources :dhcps
    resources :tc_classids
    resources :flows
    resources :open_ports
    resources :forward_ports
    resources :services, :only => [:update, :index] do
      member do
        post :find
      end
    end
    resources :computers do
      member do
        post :pass
        post :block
      end
    end
    get "main" => "main#index", :as => :main
    put "main/update",          :as => :update_main
  end

  namespace :torrent do
    resources :items do
      collection do
        post :set_rate
      end
      resources :files
      resources :peers
    end
  end

  namespace :dwnl do
    resources :web_jobs do
      member do
        get :start
      end
    end
  end

  resources :fw_rules

  get 'user_groups' => 'user_groups#index', :as => :user_groups
  post 'user_group/:user_id/:group_id' => 'user_groups#update', :as => :update_user_group
  get 'group_permissions/' => 'group_permissions#index', :as => :group_permissions
  post 'group_permission/' => 'group_permissions#update', :as => :group_permission

  resources :users
  resource :session

  root 'sessions#new'
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/login' => 'sessions#new', :as => :login
end

app/models/r_torrent/file.rb
class RTorrent::File < RTorrent::Base
  METHODS = {
    :get_completed_chunks => :completed_chunks,
    :get_frozen_path => :frozen_path,
    :is_created => :created,
    :is_open => :open,
    :get_last_touched => :last_touched,
    :get_match_depth_next => :match_depth_next,
    :get_match_depth_prev => :match_depth_prev,
    :get_offset => :offset,
    :get_path => :path,
    :get_path_components => :path_components,
    :get_path_depth => :path_depth,
    :get_priority => :priority,
    :get_range_first => :range_first,
    :get_range_second => :range_second,
    :get_size_bytes => :size_bytes,
    :get_size_chunks => :size_chunks,
  }.freeze

  PRIORITIES = { 
    'off' => 0,
    'normal' => 1,
    'high' => 2,
  }
  
  attr_accessor *METHODS.values
  attr_accessor :hash, :chunk_size
  alias_method :id, :hash

  def initialize args=nil, hash=nil
    return if args.nil?
    METHODS.values.each_with_index do |m, i|
      send(:"#{m.to_s}=", args[i])
    end
    self.hash = hash
    self.chunk_size = call('d.get_chunk_size', hash)
  end
  
  def bytes
    size_chunks * chunk_size
  end

  def bytes_completed
    completed_chunks * chunk_size
  end
  
  def percent_complete
    ((completed_chunks.to_f/size_chunks.to_f) * 100).to_i.to_s + '%'
  end
  
  def self.remote_methods
    METHODS.keys.map{|k| "#{prefix}#{k.to_s}="}
  end
  
  def self.prefix
    "f."
  end
  
  def set_priority index, prio
    call("f.set_priority", hash, index, prio.to_i)
  end
end

app/controllers/torrent/files_controller.rb
class Torrent::FilesController < Torrent::BaseController
  def index
    @files = RTorrent::Item.new(params[:item_id]).files
  end

  def update
    files = RTorrent::Item.new(params[:item_id]).files
    params[:priorities].each do |i, prio|
      files[i.to_i].set_priority i.to_i, prio
    end
    redirect_to torrent_files_path(params[:item_id])
  end
end

app/views/files/index.html.erb
<% content_for :col1 do %>
  <%= render :partial => 'menus/torrent' -%>
<% end %>

<% content_for :col2 do %>
<h1>Listing torrent files</h1>

<%= form_tag torrent_file_path(params[:torrent_id], 0), :method => :put do %>

<table class="centerAll">
  <tr>
    <th>Name</th>
    <th>Size</th>
    <th>Downloaded</th>
    <th>Done</th>
    <th>Priority</th>
  </tr>

<% @files.each_with_index do |f, i| %>
  <tr>
    <td><%= label_tag("file_#{i}", h(f.path)) %></td>
    <td><%=h f.bytes.to_mb -%></td>
    <td><%=h f.bytes_completed.to_mb %></td>
    <td><%=h f.percent_complete %></td>
    <td><%= select_tag "priorities[#{i}]", options_for_select(RTorrent::File::PRIORITIES, f.priority) %></td>
  </tr>
<% end %>
</table>

<%= submit_tag "Update" %>

<% end %>

<br />

<%= link_to 'Back', torrents_path %>
<% end %>